project:
  type: website

website:
  page-navigation: true
  title: "BSMM-8740 - Fall 2024"
  description: "Homepage for BSMM-8740: Data Analytic Methods & Algorithms."
  site-url: "https://bsmm-8740-fall-2024.github.io/osb/"

  repo-url: https://github.com/bsmm-8740-fall-2024/osb
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@lodette"
    image: "images/twitter-card.png"

  page-footer:
    right: "This design is modified from [a course at Duke](https://sta210-s22.github.io/website/)."
    left: "&copy; Copyright 2022, Mine Ã‡etinkaya-Rundel used under [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/)"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/BSMM-8740.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bsmm-8740-fall-2024
        text: "GitHub organization"
      - icon: person-fill
        text: "Brightspace"
        menu:
          - text: Discussion forum
            url: https://brightspace.uwindsor.ca/d2l/le/144921/discussions/List
          - text: Assignments
            url: https://brightspace.uwindsor.ca/d2l/lms/dropbox/admin/folders_manage.d2l?ou=144921
          - text: Home
            url: https://brightspace.uwindsor.ca/d2l/home/144921

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-faq.qmd
            text: FAQ
      - section: "Weekly materials"
        contents:
          - href: weeks/BSMM_8740_week_1.qmd
            text: "Week 1"
          - href: weeks/BSMM_8740_week_2.qmd
            text: "Week 2"
          - href: weeks/BSMM_8740_week_3.qmd
            text: "Week 3"
          - href: weeks/BSMM_8740_week_4.qmd
            text: "Week 4"
          - href: weeks/BSMM_8740_week_5.qmd
            text: "Week 5"
          - href: weeks/BSMM_8740_week_6.qmd
            text: "Week 6"
          - href: weeks/BSMM_8740_week_7.qmd
            text: "Week 7"
          - href: weeks/BSMM_8740_week_8.qmd
            text: "Week 8"
          - href: weeks/BSMM_8740_week_9.qmd
            text: "Week 9"
          - href: weeks/BSMM_8740_week_10.qmd
            text: "Week 10"
          - href: weeks/BSMM_8740_week_11.qmd
            text: "Week 11"
      - section: "Supplemental notes"
        contents:
          - href: supplemental/slr-derivations.qmd
            text: SLR derivations
          - href: supplemental/model-diagnostics-matrix.qmd
            text: Model diagnostics
          - href: supplemental/mlr-matrix.qmd
            text: MLR matrix notation
          - href: supplemental/log-transformations.qmd
            text: Log transformations
          - href: supplemental/model-selection-criteria.qmd
            text: Model selection criteria
          - href: https://www.cs.cmu.edu/~10715-f18/lectures/pca-2018.pdf
            text: PCA, KPCA, and ICA
          - href: https://towardsdatascience.com/qr-matrix-factorization-15bae43a6b2
            text: QR decomposition

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    html-math-method:
      method: mathjax

freeze: auto

editor: visual